import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Landing from './landing/landing'
import axios from 'axios'

export default function Home(props) {

  return (
    <>
      <Head>
        <title>Next Auth Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="referrer" content="no-referrer" />
      </Head>
      <main>
        <Landing menu={props.menu} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  let data

  const request = await axios.get(`${process.env.APP_URL}/api/menu/getAllMenu`)

  if(request.data.success) {
    data = request.data.menu
  }

  if(data) {
    return {props: {menu: data}}
  }
}